### PR TITLE
Add 2D elastix models for conversion

### PR DESCRIPTION
**Pull request by NHPatterson**
This PR takes the logic from the 3D conversions from `elastix` to `imglib2` and makes it applicable to 2D conversions for elastix's affine and euler transforms. I can also add similarity as well. I'm not sure the best way to test these conversions actually work in practice rather than solely in principle.

### CODE REVIEW

**Comment by bogovicj** [comment]
thanks @NHPatterson

**Comment by NicoKiaru** [comment]
Thanks @NHPatterson ! And indeed it would be a good very good idea to include some tests. 

@bogovicj I remembered that you did something with comparing your imglib2 implementation to the output from transformix, right ?

Do you think this could be a good idea  here ? Maybe we can add dependencies to the test scope for this purpose ?

ping @tischi

**Comment by bogovicj** [comment]
> I remembered that you did something with comparing your imglib2 implementation to the output from transformix, right ?

Correct, it's in the bspline branch at the moment, [here](https://github.com/image-transform-converters/image-transform-converters/blob/bspline/src/scripts/compareBSplineTransform).  I'm happy to generalize and make this a proper maven test.

**Comment by NicoKiaru** [comment]
Damned, I forgot this PR. I've just redone something similar - stupid me. I'll merge it and fix the merging issues.

**Comment by NicoKiaru** [comment]
Thanks @NHPatterson and sorry for the delay. Don't hesitate to ping us back if you do not hear from us.

I included your PR and just modified a bit the logic to facilitate the conversion from Euler2D to AffineTransform3D.

**Pull request merged**
